name: "Lint"

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - ".prettierignore"
      - "MANIFEST.in"
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Debug event.json"
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        continue-on-error: true
        run: env

      - name: "Setup Python 3.13"
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install Project"
        run: |
          python -m pip install -U pip
          python -m pip install --group dev
          python -m pip install -e .
          python -m pip list

      - name: "Debug"
        continue-on-error: true
        run: |
          python -V
          which python
          echo "::group::pip list"
          python -m pip list
          echo "::endgroup::"

      - name: "astral-sh/ruff"
        if: ${{ !cancelled() }}
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v3.5.1
        with:
          version: latest

      - name: "astral-sh/ty"
        if: ${{ !cancelled() }}
        run: |
          ty check --python "$(which python)" -v

      - name: "psf/black"
        if: ${{ !cancelled() }}
        uses: psf/black@stable

      - name: "isort"
        if: ${{ !cancelled() }}
        uses: isort/isort-action@24d8a7a51d33ca7f36c3f23598dafa33f7071326 # v1.1.1

      - name: "mypy"
        if: ${{ !cancelled() }}
        run: |
          mypy src

      - name: "bandit"
        if: ${{ !cancelled() }}
        run: |
          bandit -c pyproject.toml -r src

      - name: "validate-pyproject"
        if: ${{ !cancelled() }}
        run: |
          validate-pyproject pyproject.toml

      - name: "tombi"
        if: ${{ !cancelled() }}
        run: |
          tombi lint

      - name: "yamllint"
        if: ${{ !cancelled() }}
        run: |
          echo "::group::List Files"
          yamllint -d .github/yamllint.yaml --list-files .
          echo "::endgroup::"
          yamllint -d .github/yamllint.yaml .

      - name: "prettier"
        if: ${{ !cancelled() }}
        run: |
          echo "::group::Install"
          npm install prettier
          echo "::endgroup::"
          npx prettier --check .

      - name: "actionlint"
        if: ${{ !cancelled() }}
        uses: cssnr/actionlint-action@v1
        with:
          shellcheck_opts: -e SC2012

      - name: "pytest"
        if: ${{ !cancelled() }}
        id: coverage
        run: |
          coverage run -m pytest
          coverage xml
          coverage report -m

      - name: "codecov"
        if: ${{ !cancelled() && steps.coverage.outcome == 'success' }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
